# Generated by Django 4.2.7 on 2025-12-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0005_add_password_to_newadmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam_Title', models.CharField(max_length=255)),
                ('Exam_Type', models.CharField(max_length=255)),
                ('Exam_Date', models.DateTimeField()),
                ('Exam_Time', models.TimeField()),
                ('Exam_Duration', models.IntegerField()),
                ('Exam_Marks', models.IntegerField()),
                ('Exam_Description', models.TextField(blank=True)),
                ('Exam_Location', models.CharField(max_length=255)),
                ('Exam_Status', models.CharField(max_length=255)),
                ('Exam_Created_At', models.DateTimeField(auto_now_add=True)),
                ('Exam_Updated_At', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'examination_management',
                'verbose_name': 'Examination Management',
                'verbose_name_plural': 'Examination Management',
                'ordering': ['-Exam_Created_At'],
            },
        ),
    ]
