# Generated by Django 4.2.7 on 2025-12-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0006_examination_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination_management',
            name='Exam_Class',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='examination_management',
            name='Exam_Subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
