# Generated by Django 4.2.7 on 2025-12-12 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0007_examination_management_exam_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('tuition', 'Tuition'), ('transport', 'Transport'), ('laboratory', 'Laboratory'), ('examination', 'Examination'), ('library', 'Library'), ('sports', 'Sports'), ('hostel', 'Hostel'), ('uniform', 'Uniform'), ('other', 'Other')], default='tuition', max_length=50)),
                ('grade', models.CharField(help_text='Class/Grade of the student', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half-yearly', 'Half-Yearly'), ('yearly', 'Yearly'), ('one-time', 'One-Time')], default='monthly', max_length=20)),
                ('due_date', models.DateField()),
                ('late_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Late fee amount if payment is delayed', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Additional description for the fee')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid so far', max_digits=10)),
                ('paid_date', models.DateField(blank=True, help_text='Date when payment was made', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(db_column='student_id', help_text='Student associated with this fee', on_delete=django.db.models.deletion.CASCADE, related_name='management_fees', to='management_admin.student')),
            ],
            options={
                'verbose_name': 'Fee',
                'verbose_name_plural': 'Fees',
                'db_table': 'management_fees',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
    ]
