# Generated by Django 4.2.7 on 2025-12-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0011_ensure_student_id_varchar_alphanumeric'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, help_text='Grade/Level of the student', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newadmission',
            name='student_id',
            field=models.CharField(help_text='Student ID (Primary Key)', max_length=100, primary_key=True, serialize=False),
        ),
    ]
