# Generated by Django 4.2.7 on 2025-12-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0012_add_grade_to_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(help_text='Student ID from NewAdmission (Primary Key)', max_length=100, primary_key=True, serialize=False),
        ),
    ]
