# Generated by Django 4.2.7 on 2025-12-12 12:04
# Modified to handle column type conversion from UUID to VARCHAR

from django.db import migrations, models
import django.db.models.deletion


def convert_student_id_column_type(apps, schema_editor):
    """Convert student_id column in management_fees from UUID to VARCHAR(254) if needed"""
    with schema_editor.connection.cursor() as cursor:
        # Check current column type
        cursor.execute("""
            SELECT data_type, is_nullable
            FROM information_schema.columns 
            WHERE table_name = 'management_fees' AND column_name = 'student_id';
        """)
        result = cursor.fetchone()
        
        if result and result[0] == 'uuid':
            # Step 1: Drop foreign key constraint first
            cursor.execute("""
                SELECT constraint_name
                FROM information_schema.table_constraints
                WHERE table_name = 'management_fees'
                AND constraint_type = 'FOREIGN KEY'
                AND constraint_name LIKE '%student%';
            """)
            fk_result = cursor.fetchone()
            if fk_result:
                constraint_name = fk_result[0]
                cursor.execute(f'ALTER TABLE management_fees DROP CONSTRAINT IF EXISTS {constraint_name};')
            
            # Step 2: Make column nullable FIRST (before type conversion)
            cursor.execute("""
                ALTER TABLE management_fees 
                ALTER COLUMN student_id DROP NOT NULL;
            """)
            
            # Step 3: Set all values to NULL first (since we can't map UUIDs to emails)
            cursor.execute("""
                UPDATE management_fees 
                SET student_id = NULL;
            """)
            
            # Step 4: Convert UUID column to VARCHAR(254)
            # Now we can safely convert since all values are NULL
            cursor.execute("""
                ALTER TABLE management_fees 
                ALTER COLUMN student_id TYPE VARCHAR(254) USING student_id::text;
            """)
            
            # Step 5: Recreate foreign key constraint pointing to students.email
            # Note: This will allow NULLs since we made the column nullable
            cursor.execute("""
                ALTER TABLE management_fees 
                ADD CONSTRAINT management_fees_student_id_fk 
                FOREIGN KEY (student_id) REFERENCES students(email) ON DELETE CASCADE;
            """)


def reverse_convert_student_id(apps, schema_editor):
    """Reverse migration - convert back to UUID (not fully reversible)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0015_update_foreign_keys_to_email'),
    ]

    operations = [
        # First, convert the database column type if needed
        migrations.RunPython(convert_student_id_column_type, reverse_convert_student_id),
        # Then update the Django model field
        migrations.AlterField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(help_text='Student associated with this fee', on_delete=django.db.models.deletion.CASCADE, related_name='management_fees', to='management_admin.student'),
        ),
    ]
