# Generated by Django 4.2.7 on 2025-12-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0016_alter_fee_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newadmission',
            name='fees',
        ),
    ]
