# Generated by Django 4.2.7 on 2025-12-12 12:25
# Modified to populate existing records

from django.db import migrations, models


def populate_fee_fields(apps, schema_editor):
    """Populate total_amount and amount_to_be_paid for existing records"""
    Fee = apps.get_model('management_admin', 'Fee')
    for fee in Fee.objects.all():
        # Set total_amount to amount if not set
        if fee.total_amount is None:
            fee.total_amount = fee.amount
        # Set amount_to_be_paid to due_amount if not set
        if fee.amount_to_be_paid is None:
            fee.amount_to_be_paid = fee.due_amount if fee.due_amount else (fee.amount - fee.paid_amount)
        fee.save()


def reverse_populate_fee_fields(apps, schema_editor):
    """Reverse migration - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0017_remove_newadmission_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='amount_to_be_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount to be paid', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount of the fee', max_digits=10, null=True),
        ),
        migrations.RunPython(populate_fee_fields, reverse_populate_fee_fields),
    ]
