# Generated by Django 4.2.7 on 2025-12-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0019_rename_amount_to_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount of the fee', max_digits=10),
        ),
        migrations.AlterField(
            model_name='newadmission',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Grade of the student (A, B, C, or D)', max_length=1, null=True),
        ),
    ]
