# Generated by Django 4.2.7 on 2025-12-15 05:46

from django.db import migrations, models


def populate_student_name_section(apps, schema_editor):
    """Populate student_name and section from student relationship"""
    Fee = apps.get_model('management_admin', 'Fee')
    Student = apps.get_model('management_admin', 'Student')
    
    for fee in Fee.objects.all():
        if fee.student_id:
            try:
                student = Student.objects.get(pk=fee.student_id)
                fee.student_name = student.student_name or ''
                # Try to get section from student
                if hasattr(student, 'section') and student.section:
                    fee.section = student.section
                elif hasattr(student, 'applying_class') and student.applying_class:
                    # Extract section from class if format is like "Class 1-A" or "1-A"
                    class_str = str(student.applying_class)
                    if '-' in class_str:
                        fee.section = class_str.split('-')[-1]
                fee.save()
            except Student.DoesNotExist:
                # If student doesn't exist, leave fields empty
                fee.student_name = ''
                fee.section = ''
                fee.save()


def reverse_populate_student_name_section(apps, schema_editor):
    """Reverse migration - clear the fields"""
    Fee = apps.get_model('management_admin', 'Fee')
    Fee.objects.all().update(student_name='', section='')


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0020_add_grade_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='section',
            field=models.CharField(blank=True, help_text='Student section (auto-populated from student)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='student_name',
            field=models.CharField(blank=True, help_text='Student name (auto-populated from student)', max_length=255),
        ),
        migrations.RunPython(populate_student_name_section, reverse_populate_student_name_section),
    ]
