# Generated by Django 4.2.7 on 2025-12-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0021_add_student_name_section_to_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='section',
        ),
        migrations.AddField(
            model_name='fee',
            name='applying_class',
            field=models.CharField(blank=True, help_text='Student class (auto-populated from student)', max_length=50),
        ),
        migrations.AlterField(
            model_name='fee',
            name='grade',
            field=models.CharField(help_text='Grade of the student (A, B, C, D)', max_length=50),
        ),
    ]
