# Generated by Django 4.2.7 on 2025-12-15 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0022_remove_section_add_applying_class_to_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='amount_to_be_paid',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='paid_date',
        ),
        migrations.AddField(
            model_name='fee',
            name='current_paying_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current payment being made', max_digits=10),
        ),
        migrations.AddField(
            model_name='fee',
            name='last_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Last payment amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='fee',
            name='last_paid_date',
            field=models.DateField(blank=True, help_text='Date of last payment', null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount paid so far (sum of all payments)', max_digits=10),
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, help_text='Amount paid in this transaction', max_digits=10)),
                ('payment_date', models.DateField(help_text='Date when payment was made')),
                ('notes', models.TextField(blank=True, help_text='Additional notes for this payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee', models.ForeignKey(help_text='Fee associated with this payment', on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='management_admin.fee')),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment Histories',
                'db_table': 'payment_history',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
