# Generated by Django 4.2.7 on 2025-12-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0023_add_payment_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='current_paying_amount',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='last_paid_amount',
        ),
    ]
