# Generated by Django 4.2.7 on 2025-12-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0024_remove_unwanted_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='student_id_string',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Student ID as string (e.g., STUD-005) - indexed for faster lookups', max_length=100),
        ),
    ]
