# Generated by Django 4.2.7 on 2025-12-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0025_add_student_id_string_to_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Receipt number for this payment', max_length=100),
        ),
    ]
